import React from 'react'

export default function About(props) {
  return (
    <div className='container'>
      <h1 style={{color:props.mode==='light'?'black':'white'}}>About</h1>
      <p style={{color:props.mode==='light'?'black':'white'}}>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia voluptatem, eos, officia eius illo voluptate odio magni, aperiam quis ut a sed! Non nam nostrum adipisci excepturi laborum vero nulla debitis ipsam explicabo aperiam, facere, ab similique, minus quae ad quasi. Odit, numquam? Odit aliquam quo quod animi blanditiis doloribus sint provident repellat! Earum soluta dolorum modi repellat dolore eum ipsam ratione, aspernatur corrupti minima culpa deleniti eaque quaerat sed quo. Nobis repellendus sapiente necessitatibus dolores, perspiciatis quidem. Ipsum eos sunt iusto sapiente ex sequi mollitia corporis ipsa, distinctio animi, similique ea consectetur neque error blanditiis incidunt culpa cumque obcaecati odio enim, dolorem magnam odit at doloribus. Minima, error, reiciendis doloribus excepturi quasi nostrum iure, sit culpa accusantium voluptates impedit commodi maxime expedita quia. Sequi, quo. In tenetur eligendi qui perspiciatis rem quo blanditiis officia quod quibusdam, maxime cumque, corrupti assumenda placeat culpa quasi beatae libero architecto. Eum autem alias ratione labore in, voluptatibus esse et quas, porro nesciunt ab eius iste quo nulla, delectus iure cum repellat? Dolore inventore assumenda aut possimus ab. Aliquam, perspiciatis dolorum eius animi in totam quo itaque quibusdam impedit, commodi corrupti veritatis sint maxime voluptates ex labore. Unde, est. Ea tenetur error illum odio ipsa mollitia dolorum optio assumenda. Asperiores placeat, possimus ex deleniti maxime quod animi inventore consequatur omnis corrupti perspiciatis! Illo ea quos pariatur mollitia odio consequuntur assumenda enim voluptas aperiam eaque a tempore maiores, dolorem nobis ipsam, reiciendis, reprehenderit alias saepe tenetur commodi asperiores officiis fuga similique? Optio voluptatum cupiditate dolore.</p>
    </div>
  )
}
